### ISSUE TITLE
Ignoring exception in on_model callback when solving asynchronously

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#241]
```
import clingo

def on_model(m):
    print("Here1")
    a = 5 + "asd"
    print("Here2")
ctl = clingo.Control("0")
ctl.add("p", [], "1 { a; b } 1.")
ctl.ground([("p", [])])
with ctl.solve(on_model=on_model, async_=True) as handle:
    handle.wait(5)
```

This does not print "Here2" ans silently drops it.

**Comment by rkaminsk** [comment]
You have to properly cancel the search because wait won't throw the exception. The program

```python
import clingo

def on_model(m):
    print("Here1")
    a = 5 + "asd"
    print("Here2")
ctl = clingo.Control("0")
ctl.add("p", [], "1 { a; b } 1.")
ctl.ground([("p", [])])
with ctl.solve(on_model=on_model, async_=True) as handle:
    handle.wait(5)
    handle.cancel()
    print(handle.get())
```

will produce

```
Here1
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    print(handle.get())
RuntimeError: <on_model>: error: error in model callback:
  Traceback (most recent call last):
    File "test.py", line 5, in on_model
    a = 5 + "asd"
  TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by MaxOstrowski** [comment]
The `cancel()` alone seems not enought and the `get()` is necessary.
I do get the point why I should call cancel(), but in my case I do not need the solve_result, as on_model already told me a model. In this case I will never see the exception.
