### ISSUE TITLE
Calling embedded Python code from Clingo 5.5.0

### ISSUE THREAD

**Issue by andrewcropper** [potassco/clingo#302]
Calling embedded Python code from a Clingo program with Clingo 5.5.0 is either not working or the examples on your webpage are out-of-date .

I used the following example (from https://potassco.org/clingo/python-api/5.5/clingo/#embedded-python-code):

```
#script (python)

from clingo.symbol import Number

class Context:
    def inc(x):
        return Number(x.number)

    def seq(x, y):
        return [x, y]

def main(prg):
    prg.ground([("base", [])], context=Context())
    prg.solve()

#end.

p(@inc(10)).
q(@seq(1,2)).
```

I receive the error:

```
*** ERROR: (clingo): Traceback (most recent call last):
  File "/Users/andrew/.local/lib/python3.8/site-packages/clingo/script.py", line 207, in _pyclingo_main
    return _pyclingo_script_main(_ffi.cast('clingo_control_t*', ctl),
  File "/Users/andrew/.local/lib/python3.8/site-packages/clingo/script.py", line 177, in _pyclingo_script_main
    script.main(Control(_ffi.cast('clingo_control_t*', ctl)))
  File "/Users/andrew/.local/lib/python3.8/site-packages/clingo/script.py", line 138, in main
    __main__.main(control) # pylint: disable=c-extension-no-member
  File "<string>", line 13, in main
  File "/Users/andrew/.local/lib/python3.8/site-packages/clingo/control.py", line 338, in ground
    _handle_error(_lib.clingo_control_ground(
  File "/Users/andrew/.local/lib/python3.8/site-packages/clingo/_internal.py", line 61, in _handle_error
    raise handler.error[0](handler.error[1]).with_traceback(handler.error[2])
  File "/Users/andrew/.local/lib/python3.8/site-packages/clingo/control.py", line 112, in _pyclingo_ground_callback
    ret = fun(*args)
TypeError: seq() takes 2 positional arguments but 3 were given
```

**Comment by rkaminsk** [comment]
You did not copy the example carefully... :wink: Hint: self

**Comment by andrewcropper** [comment]
Ah yes. I copied it correctly, but there is mistake in the example:

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/370890/116249420-b890d600-a764-11eb-9a6d-221691acfb9d.png">

I should have spotted it myself though, sorry!

**Comment by rkaminsk** [comment]
It's fine. Please report these things. Like this they will get fixed!
