### ISSUE TITLE
Missing MessageCode with value 6 in clingo 5.5

### ISSUE THREAD

**Issue by florianfischer91** [potassco/clingo#303]
After the update to clingo 5.5 my application throws an exception during the logger callback (python API)

```
Traceback (most recent call last):
  File "C:\Users\xxx\.conda\envs\clingo5_5\lib\site-packages\clingo\core.py", line 65, in _pyclingo_logger_callback
    handler(MessageCode(code), _to_str(message))
  File "C:\Users\xxx\.conda\envs\clingo5_5\lib\enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\xxx\.conda\envs\clingo5_5\lib\enum.py", line 677, in __new__
    raise ve_exc
ValueError: 6 is not a valid MessageCode```

I think there are duplicate assignments of message codes in the MessageCode-class:

https://github.com/potassco/clingo/blob/7f065b9af58dcdbfead4cc57232ce7ac0965cee5/libpyclingo/clingo/core.py#L26
https://github.com/potassco/clingo/blob/7f065b9af58dcdbfead4cc57232ce7ac0965cee5/libpyclingo/clingo/core.py#L43

The message code for 
https://github.com/potassco/clingo/blob/7f065b9af58dcdbfead4cc57232ce7ac0965cee5/libclingo/clingo.h#L173
is probably missing

**Comment by rkaminsk** [comment]
You are right. It has to be  `Other = _lib.clingo_warning_other`.
