### ISSUE TITLE
Segfault caused by some exceptions in Python

### ISSUE THREAD

**Issue by peschue** [potassco/clingo#42]
The following program works nicely, also exceptions test1 and test2 behave as expected (they are passed through and arrive again at the toplevel Python where they abort the program).

However, if I activate exception test3 this causes a segfault instead of passing on and printing the exception.

```
#!/usr/bin/python3

import clingo

def main(prg):
    def on_model(m):
        print("on_model got model "+str(m))
        #raise Exception("test1")

    class GroundProgramObserver:
      def begin_step(self):
        print("gpo begin")
        #raise Exception("test2")
      def end_step(self):
        print("gpo end")
        #raise Exception("test3")

    prg.configuration.solve.models = 0 
    prg.add("base", [], "2 { a; b; c; d }.")
    obs = GroundProgramObserver()
    prg.register_observer(obs)
    prg.ground([("base", [])])
    prg.solve(on_model=on_model)

main(clingo.Control())
```

The backtrace in gdb is as follows (built using clingo release 5.2.0 package and Python 3.5.2 on Ubuntu 16.04):
```
gpo begin
gpo end

Program received signal SIGSEGV, Segmentation fault.
0x00000000005bb65a in PyErr_Fetch ()
(gdb) bt
#0  0x00000000005bb65a in PyErr_Fetch ()
#1  0x00007ffff636133f in (anonymous namespace)::handle_cxx_error_(std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >&) [clone .constprop.550] () from /home/ps/.hexlite/lib/libpyclingo.so.1
#2  0x00007ffff6361a90 in (anonymous namespace)::handle_cxx_error(char const*, char const*) ()
   from /home/ps/.hexlite/lib/libpyclingo.so.1
#3  0x00007ffff637c40f in (anonymous namespace)::observer_end_step(void*) () from /home/ps/.hexlite/lib/libpyclingo.so.1
#4  0x00007ffff5e3b528 in (anonymous namespace)::Observer::endStep() () from /home/ps/.hexlite/lib/libclingo.so.1
#5  0x00007ffff5ed5301 in Gringo::Output::(anonymous namespace)::BackendTee::endStep() ()
   from /home/ps/.hexlite/lib/libclingo.so.1
#6  0x00007ffff5edbb56 in Gringo::Output::OutputBase::endStep(bool, Gringo::Logger&) ()
   from /home/ps/.hexlite/lib/libclingo.so.1
#7  0x00007ffff5e32197 in Gringo::ClingoControl::prepare(std::vector<std::pair<Gringo::Symbol, bool>, std::allocator<std::pair<Gringo::Symbol, bool> > >&&) () from /home/ps/.hexlite/lib/libclingo.so.1
```

With Python 2 I also observe such segfaults, I did not test if they occur in the same functions, though. But in some places, throwing exceptions clearly works, in some places it clearly does not.

**Comment by rkaminsk** [comment]
I was releasing Python's GIL before handling the exception, which was causing the segfaults. Fixed in wip branch.

PS: that was issue 42!!!

**Comment by peschue** [comment]
I'm feeling lucky!

Thank you, with your bugfix, debugging suddenly is much easier. :)
